# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Author

# Model Form Field configuration
form: $/acme/bookshop/models/author/fields.yaml

# Model Class name
modelClass: Acme\Bookshop\Models\Author

# Default redirect location
defaultRedirect: acme/bookshop/authors

# Create page
create:
    title: Create Author
    redirect: acme/bookshop/authors/update/:id
    redirectClose: acme/bookshop/authors

# Update page
update:
    title: Edit Author
    redirect: acme/bookshop/authors
    redirectClose: acme/bookshop/authors

# Preview page
preview:
    title: Preview Author